version: '3.6'

services:
  web:
    build:
      context: .
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - .:/projeto
    environment:
      - PYTHONPATH=/projeto
      - FLASK_APP=src/flask_app/app.py
      - FLASK_ENV=development
      - TEMPLATES_AUTO_RELOAD=True
      - PYTHONUNBUFFERED=1
      - APPLY_TO_ALL=True
    ports:
      - 5000:5000
